//Uses the Localhost

###Get All groceries
GET http://localhost:3000/groceries

###Get recipe by id
GET http://localhost:3000/groceries/68d65f4648053ec428652d88

###Create groceries
POST http://localhost:3000/groceries
Content-Type: application/json

{
  "name": "Ice Cream",
  "category": "Freezer",
  "quantity": 2,
  "unit": "tubs",
  "purchased": false
}


### Update groceries
PUT http://localhost:3000/groceries/68d84645a765e13a415de323
Content-Type: application/json

{
  "name": "Ice Cream Bars",
  "category": "Freezer",
  "quantity": 3,
  "unit": "tubs",
  "purchased": false
}

###Delete groceries by id
DELETE http://localhost:3000/groceries/68d84645a765e13a415de323

